### ISSUE TITLE
Agregar totalizadores

### ISSUE THREAD

**Issue by belluccifranco** [open-commercial/sic-ops-web#131]
Agregar los siguientes totalizadores en las vistas correspondientes:

- Agregar "Valor del Stock" en el listado de productos
- Agregar en listado de facturas de compra: "Total Facturado" y "Total IVA Compra"
- Agregar en recibos de compras "Total"
- Agregar en listado de NCC: "Total IVA Credito" y "Total Credito"
- Agregar en listado de NDC: "Total IVA Debito" y "Total Debito"
- Agregar en listado de facturas de venta: "Total Facturado" y "Total IVA Venta"
- Agregar en recibos de ventas "Total"
- Agregar en listado de NCV: "Total IVA Credito" y "Total Credito"
- Agregar en listado de NDV: "Total IVA Debito" y "Total Debito"
- Agregar en listado de gastos: "Total"

El totalizador debe ir en el "escalon" de abajo al paginator, alineados siempre a la derecha
![image](https://user-images.githubusercontent.com/1295105/201781250-86507002-5d02-415c-8fce-87958cbdeea1.png)

Usar el style de Caja (verde/rojo)
![image](https://user-images.githubusercontent.com/1295105/201781379-d41c2e40-2e47-465b-84fc-79fc4595c810.png)

**Comment by k31kur0n0** [comment]
Agregar "Valor del Stock" en el listado de productos 
POST "/productos/valor-stock/criteria" - RequestBody BusquedaProductoCriteria criteria

Agregar en listado de facturas de compra: "Total Facturado" y "Total IVA Compra"
POST "/facturas/compras/total-facturado/criteria" - RequestBody BusquedaFacturaCompraCriteria criteria
POST "/facturas/compras/total-iva/criteria" - RequestBody BusquedaFacturaCompraCriteria criteria

Agregar en recibos de compras "Total"
POST "/recibos/total/criteria" - RequestBody BusquedaReciboCriteria criteria (Movimiento.COMPRA)

Agregar en listado de NCC: "Total IVA Credito" y "Total Credito"
POST "/notas/total-iva-credito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.COMPRA)
POST "/notas/total-credito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.COMPRA)

Agregar en listado de NDC: "Total IVA Debito" y "Total Debito"
POST "/notas/total-iva-debito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.COMPRA)
POST "/notas/total-debito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.COMPRA)

Agregar en listado de facturas de venta: "Total Facturado" y "Total IVA Venta"
POST "/facturas/ventas/total-facturado/criteria" - RequestBody BusquedaFacturaVentaCriteria criteria
POST "/facturas/ventas/total-iva/criteria" - RequestBody BusquedaFacturaVentaCriteria criteria

Agregar en recibos de ventas "Total"
POST "/recibos/total/criteria" - RequestBody BusquedaReciboCriteria criteria (Movimiento.VENTA)

Agregar en listado de NCV: "Total IVA Credito" y "Total Credito"
POST "/notas/total-iva-credito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.VENTA)
POST "/notas/total-credito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.VENTA)

Agregar en listado de NDV: "Total IVA Debito" y "Total Debito"
POST "/notas/total-iva-debito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.VENTA)
POST "/notas/total-debito/criteria" - RequestBody BusquedaNotaCriteria criteria (Movimiento.VENTA)

Agregar en listado de gastos: "Total"
POST "/gastos/total/criteria" - RequestBody BusquedaGastoCriteria criteria (Movimiento.VENTA)

**Comment by belluccifranco** [comment]
@facundososalopez 
- El spinner nuevo para totalizadores debe estar alineado al centro
- Falta aplicar format a la fecha de Recibos de Venta
![image](https://user-images.githubusercontent.com/1295105/205171198-a8122750-2b81-4a15-8a31-03394cb48a0e.png)
- No funciona correctamente el filtro por fecha de Gastos, cuando solo utiliza fecha desde o hasta (un lado solamente)
- Debe mostrar $0 cuando el resultado de la busqueda no tiene registros, en:
Valor del Stock en Productos
Recibos de compra
Recibos de venta
Gastos
